### ISSUE TITLE
Don't use `plot_t_band` for all models in `plot_model`

### ISSUE THREAD

**Issue by michaelosthege** [JuBiotech/calibr8#21]
Here, the `plot_model` function tries to use `plot_t_band` irrespective of the actual noise model:

https://github.com/JuBiotech/calibr8/blob/master/calibr8/utils.py#L326-L365

Instead of hard-coding a `plot_xyz_band`, we can probabily generalize over al continuous distributions by using the `DistributionMixin.scipy_dist` class attribute that comes with each model.

@lhelleckes would you like to take a look at this?

**Comment by lhelleckes** [comment]
Alright, here are my ideas so far:

- the `plot_model` function can be used for all dists, but only the continuous one create the band.
- for the continuous ones, we need a ppf function defined. If this is not the case, we could allow the user to specify upper and lower bounds manually, which might be error prone. Opinions on that?

**Comment by michaelosthege** [comment]
>     * the `plot_model` function can be used for all dists, but only the continuous one create the band.

The plot for discrete dependent variables like in https://calibr8.readthedocs.io/en/latest/Advanced_Custom_Noise_Models.html is quite different, so it would probably be a big `if/elif/else` branching early in `plot_model`?
For now I'd be fine with an informative exception on models other than `ContinuousUnivariateModel` with continuous noise. 
But if you want to support discrete noise models too, that'd be awesome 🚀

>     * for the continuous ones, we need a ppf function defined. If this is not the case, we could allow the user to specify upper and lower bounds manually, which might be error prone. Opinions on that?

Where continuous dists have a [`ppf`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.ppf.html) the discrete dists have a [`pmf`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_discrete.pmf.html). Why do you need bounds?

**Comment by lhelleckes** [comment]
Well, the bouds for the intervals of the continuous bands are what;s plotted in the end. If I check for the `.ppf` methods, we are bound to scipy dists. That's ok for the moment, the other distrubitions would then lead to exceptions at the moment. 
Let's start small with continuous ones and then go to a detailed solution

**Comment by michaelosthege** [comment]
@lhelleckes do you already have a feeling how big of a change this will be?

**Comment by michaelosthege** [comment]
Yes, implementing it just for the continuous dists having `.ppf` is fine. (I mentioned just continuous dists in the issue description too.)
