### ISSUE TITLE
add pymc v4 compatibility

### ISSUE THREAD

**Issue by lhelleckes** [JuBiotech/calibr8#23]
We use a function that will not be available in v4:
![grafik](https://user-images.githubusercontent.com/45510988/152314514-80593f53-de5f-4ac8-be13-32611ff57109.png)

Additionally, our current test CI is not testing with v4, so we should add compatibility with the v4 release.

**Comment by michaelosthege** [comment]
Relevant line from the release notes:

> logpt, logpt_sum, logp_elemwiset and nojac variations were removed. Use Model.logpt(jacobian=True/False, sum=True/False) instead.
