### ISSUE TITLE
Transfer from DCS contrib to jupyter notebook yields error

### ISSUE THREAD

**Issue by valentinsteier** [JuBiotech/calibr8#44]
![grafik](https://user-images.githubusercontent.com/107388990/173391159-6a526cf8-068d-47e0-ad5b-26b747bf42bf.png)

Copying the code from DCS contrib server yields the error in the screenshot

----

⚠ This issue is about FZJ-internal code.

**Comment by michaelosthege** [comment]
Huh, you got me. I didn't test that code.

The error was probably in this block, right?

```
```

**Comment by valentinsteier** [comment]
thanks for the quick response! works fine, does yield a warning though:
![grafik](https://user-images.githubusercontent.com/107388990/173392691-32d38740-0ba7-4824-a14d-67dcd56de228.png)

**Comment by michaelosthege** [comment]
![data says no](https://user-images.githubusercontent.com/5894642/173392977-7facd6b4-a43e-4619-821c-7341f31a039d.png)

So it wants an even more negative symmetry parameter...

But with this dataset, did you consider the `Exponential` model?
With the parametrization shown in the lower-left quadrant of the figure [in the documentation](https://calibr8.readthedocs.io/en/latest/Basic_ExponentialModel.html) this could be a rather okay fit.

(Nevertheless, your data looks ...challenging...)
