### ISSUE TITLE
Global optimisation

### ISSUE THREAD

**Issue by lhelleckes** [JuBiotech/calibr8#46]
- Add kwarg to choose solver in scripy.minimize
- Maybe even use a better toolbox?

Thanks to @maxsiska for starting this discussion. @michaelosthege Should we discuss this soon?

**Comment by michaelosthege** [comment]
I like the idea of making it easier to use optimizers other than `scipy.optimize.minimize`. `scipy.optimize.fmin` comes to mind but also the global optimizers you and @maxsiska refer to.

I'd say how to implement it depends on the signatures:
If we can internally switch between the optimizers based on a single user-provided kwarg such as `which="minimize|fmin|global`, and the results remain the same type that's cool.

But if the optimizers need different inputs, or if the result is of completely different type, then I would instead prefer to have `calibr8.fit_scipy_global`, `calibr8.fit_scipy_fmin` etc.

**Comment by michaelosthege** [comment]
> Add kwarg to choose solver in scripy.minimize

This should already be possible through [`calibr8.fit_scipy(..., minimize_kwargs=dict(...))`](https://github.com/JuBiotech/calibr8/blob/master/calibr8/optimization.py#L94)

**Comment by michaelosthege** [comment]
Closed by #54 and #57
